USE [master]
GO
ALTER DATABASE BAN_HANG SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

IF DB_ID('BAN_HANG') IS NOT NULL
BEGIN
	USE [master]
	DROP DATABASE BAN_HANG
END

CREATE DATABASE BAN_HANG
GO
USE BAN_HANG
GO

CREATE TABLE dbo.NHACUNGCAP
(
	MANCC INT IDENTITY PRIMARY KEY NOT NULL,
	TENNCC VARCHAR(50) NULL,
	SDT INT NOT NULL,
	DIACHI VARCHAR(50) NULL
)
GO

CREATE TABLE dbo.SANPHAM
(
	MASP INT IDENTITY PRIMARY KEY NOT NULL,
	TENSP VARCHAR(50) NULL,
	DONGIA FLOAT NULL,
	SLTONKHO INT NULL,
	SLTOITHIEU INT NULL,
	SLTOIDA INT NULL,
	SOLUONGTRA INT NULL,
	SOLUONGTRATOIDA INT NULL,
	NCC INT NULL,
	CONSTRAINT FK_SANPHAM_NHACUNGCAP FOREIGN KEY(NCC) REFERENCES dbo.NHACUNGCAP(MANCC)
)
GO

CREATE TABLE dbo.KHACHHANG
(
	MAKH INT IDENTITY PRIMARY KEY NOT NULL,
	TENKH VARCHAR(50) NULL,
	EMAIL VARCHAR(100) NULL,
	NGAYSINH DATE NULL,
	DIACHI VARCHAR(50) NULL
)
GO

CREATE TABLE dbo.DONHANG
(
	MADH INT IDENTITY PRIMARY KEY NOT NULL,
	NGAYLAP DATE NULL,
	TONGSOLUONG INT NULL,
	TONGTIEN FLOAT DEFAULT 0,
	TRANGTHAI INT NULL,
	--CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY(NGUOIMUA) REFERENCES dbo.KHACHHANG(MAKH)
)
GO

CREATE TABLE dbo.CHITIETDONHANG
(
	MADH INT NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NULL,
	THANHTIEN FLOAT NULL,
	CONSTRAINT PK_CTDH PRIMARY KEY(MADH, MASP),
	CONSTRAINT FK_CHITIETDONHANG_SANPHAM FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP),
	CONSTRAINT FK_CHITIETDONHANG_DONHANG FOREIGN KEY(MADH) REFERENCES dbo.DONHANG(MADH)
)
GO

CREATE TABLE dbo.BINHLUAN
(
	MABL INT IDENTITY PRIMARY KEY NOT NULL,
	HOTEN VARCHAR(50) NULL,
	EMAIL VARCHAR(100) NULL,
	DIACHI VARCHAR(500) NULL,
	NGAYBL DATETIME NULL,
	NOIDUNG TEXT NULL,
	MASP INT NULL,
	PHANLOAI INT NULL,
	CONSTRAINT FK_BINHLUAN_SANPHAM FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)
)
GO

CREATE TABLE dbo.CAMNGUOIDUNG
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	EMAIL VARCHAR(100) NULL,
)

CREATE TABLE dbo.LOAINHANVIEN
(
	MALOAINV INT IDENTITY PRIMARY KEY NOT NULL,
	TENLOAINV VARCHAR(20) NULL
)
GO

CREATE TABLE dbo.NHANVIEN
(
	MANV INT IDENTITY PRIMARY KEY NOT NULL,
	TENNV VARCHAR(50) NULL,
	DIACHI VARCHAR(50) NULL,
	NGAYSINH DATE NULL,
	TIENLUONG FLOAT DEFAULT 0,
	SDT INT NULL,
	LOAINV INT NOT NULL,
	USERNAME VARCHAR(10),
	PASS VARCHAR(8),
	CONSTRAINT FK_NHANVIEN_LOAINV FOREIGN KEY(LOAINV) REFERENCES dbo.LOAINHANVIEN(MALOAINV)
)
GO

CREATE TABLE dbo.LICHSU_NHAP_NHACUNGCAP
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	MASP INT NULL,
	NGAYNHAP DATE NULL,
	SOLUONG INT NULL,
	NVPHUTRACH INT NULL,
	XACNHAN INT NULL,
	NCC INT NULL,
	LYDONHAPHANG VARCHAR(50) NULL,
	QUANLY INT NULL,
	CONSTRAINT CHK_XACNHAN CHECK (XACNHAN = 0 OR XACNHAN=1 OR XACNHAN=2),
	CONSTRAINT FK_NHAPHANG_SANPHAM FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP),
	CONSTRAINT FK_NHAPHANG_NHANVIEN FOREIGN KEY(NVPHUTRACH) REFERENCES dbo.NHANVIEN(MANV),
	CONSTRAINT FK_NHAPHANG_NCC FOREIGN KEY(NCC) REFERENCES dbo.NHACUNGCAP(MANCC),
	CONSTRAINT FK_LSNHAPNCC_NHANVIEN FOREIGN KEY (QUANLY) REFERENCES dbo.NHANVIEN(MANV)
)
GO

CREATE TABLE dbo.LICHSU_TRA_NHACUNGCAP
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NULL,
	LYDOTRA TEXT NULL,
	NGAYTRA DATE NULL,
	NVPHUTRACH INT NULL,
	XACNHAN INT NULL,
	NCC INT NULL,
	QUANLY INT NULL,
	CONSTRAINT CHK_XACNHANTRA CHECK (XACNHAN = 0 OR XACNHAN=1 OR XACNHAN=2),
	CONSTRAINT FK_TRAHANG_SANPHAM FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP),
	CONSTRAINT FK_TRAHANG_NHANVIEN FOREIGN KEY(NVPHUTRACH) REFERENCES dbo.NHANVIEN(MANV),
	CONSTRAINT FK_TRAHANG_NCC FOREIGN KEY(NCC) REFERENCES dbo.NHACUNGCAP(MANCC),
	CONSTRAINT FK_LSTRANCC_NHANVIEN FOREIGN KEY(QUANLY) REFERENCES dbo.NHANVIEN(MANV)
)
GO


CREATE TABLE dbo.LICHSU_THANHTOAN_KHACHHANG
(
	MAKH INT NULL,
	TONGTIEN FLOAT NULL,
	HINHTHUC VARCHAR(10) NULL,
	THOIGIAN DATETIME NULL,
	SOTK VARCHAR(15) NULL,
	NGANHANG VARCHAR(50) NULL,
	TENCHUTHE VARCHAR(50) NULL,
	MADH INT  NULL,
	CONSTRAINT CHK_HINHTHUC CHECK(HINHTHUC = 'COD' OR HINHTHUC='ONLINE'),
	CONSTRAINT FK_LS_KHACHHANG FOREIGN KEY(MAKH) REFERENCES dbo.KHACHHANG(MAKH),
	CONSTRAINT FK_DONHANG_LS FOREIGN KEY(MADH) REFERENCES dbo.DONHANG(MADH)
)
GO


CREATE TABLE dbo.LICHSU_KHACH_TRAHANG
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	MAKH INT NULL,
	MASP INT NULL,
	SOLUONG INT NULL,
	LYDOTRA TEXT NULL,
	NGAYTRA DATE NULL,
	NVPHUTRACH INT NULL,
	CONSTRAINT FK_KHACH_TRA FOREIGN KEY(MAKH) REFERENCES dbo.KHACHHANG(MAKH),
	CONSTRAINT FK_LS_NV FOREIGN KEY(NVPHUTRACH) REFERENCES dbo.NHANVIEN(MANV)
)
GO

CREATE TABLE dbo.HOPDONG_QUANGCAO
(
	MAHOPDONG INT IDENTITY PRIMARY KEY NOT NULL,
	TENDOITAC VARCHAR(50) NULL,
	NGAYLAP DATE NULL,
	VITRIDANGQC TEXT NULL,
	THOIHAN INT NULL
)
GO

CREATE TABLE dbo.TINDANG_QUANGCAO
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	NOIDUNG TEXT NULL,
	NGUOIDANG INT NULL,
	NGAYDANG DATE NULL,
	NGAYSUA DATE NULL,
	MAHOPDONG INT NULL,
	CONSTRAINT FK_TDQUANGCAO_NHANVIEN FOREIGN KEY(NGUOIDANG) REFERENCES dbo.NHANVIEN(MANV),
	CONSTRAINT FK_TDQUANGCAO_HOPDONG FOREIGN KEY(MAHOPDONG) REFERENCES dbo.HOPDONG_QUANGCAO(MAHOPDONG)
)
GO


CREATE TABLE dbo.TINNHAN_QUANGCAO
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	NOIDUNG TEXT NULL,
	NGUOIGUI INT NULL,
	NGAYGUI DATE NULL,
	NGUOINHAN INT NULL,
	CONSTRAINT FK_TNQUANGCAO_NHANVIEN FOREIGN KEY(NGUOIGUI) REFERENCES dbo.NHANVIEN(MANV),
	CONSTRAINT FK_TNQUANGCAO_KHACHHANG FOREIGN KEY(NGUOINHAN) REFERENCES dbo.KHACHHANG(MAKH)
)
GO

ALTER TABLE dbo.SANPHAM
ADD NVQL INT NULL
GO

ALTER TABLE dbo.SANPHAM
ADD CONSTRAINT FK_SANPHAM_NHANVIEN FOREIGN KEY(NVQL) REFERENCES dbo.NHANVIEN(MANV)
GO

ALTER TABLE dbo.NHANVIEN
ADD NVQL INT NULL
GO

ALTER TABLE dbo.NHANVIEN
ADD CONSTRAINT FK_QUANLY_NHANVIEN FOREIGN KEY(NVQL) REFERENCES dbo.NHANVIEN(MANV)

INSERT into NHACUNGCAP (TENNCC, SDT, DIACHI) values ('Kare', 6117752, '72365 Hoffman Hill')
insert into NHACUNGCAP (TENNCC, SDT, DIACHI) values ('Skinix', 1948818, '9 Clarendon Parkway')
insert into NHACUNGCAP (TENNCC, SDT, DIACHI) values ('Fivespan', 14368359, '9 Clyde Gallagher Point')
insert into NHACUNGCAP (TENNCC, SDT, DIACHI) values ('Skyvu', 14675806, '657 Bashford Trail')
insert into NHACUNGCAP (TENNCC, SDT, DIACHI) values ('Zooveo', 14579910, '35 Darwin Road')
GO

insert into LOAINHANVIEN (TENLOAINV) values ('Quan ly');
insert into LOAINHANVIEN (TENLOAINV) values ('Nhan vien ban hang');
insert into LOAINHANVIEN (TENLOAINV) values ('Nhan vien nhap hang');
insert into LOAINHANVIEN (TENLOAINV) values ('Nhan vien tra hang');
insert into LOAINHANVIEN (TENLOAINV) values ('Thu quy');
GO

insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Jeremy Hearsum', '295 Crownhardt Alley', '10/23/2019', 346, 23659528, 1, 'jhearsum0', '123456', NULL);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Bailie Guppey', '0787 Morning Crossing', '2/25/2020', 442, 55723001, 1, 'bguppey1', '123456', NULL);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Alisun Sottell', '3 Huxley Junction', '2/1/2020', 285, 48078760, 1, 'asottell2', '123456', NULL);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Janean Smeeton', '44514 Fremont Pass', '6/7/2020', 459, 88284635, 2, 'jsmeeton3', '123456', 1);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Bartel Winchurch', '31 American Trail', '8/4/2020', 809, 95287709, 3, 'bwi', '123456', 2);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Derril Mathys', '84387 Grim Terrace', '11/19/2019', 415, 25421071, 4, 'dmathys5', '123456', 3);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Harrietta Dionisetto', '4597 Mandrake Center', '1/26/2020', 512, 34664801, 5, 'hdion', '123456', 1);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Kathi Dury', '75593 Kim Street', '6/27/2020', 672, 37359491, 2, 'kdury7', '123456', 1);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('June Polin', '38077 Carioca Crossing', '8/11/2020', 346, 1593009, 3, 'jpolin8', '123456', 2);
insert into NHANVIEN (TENNV, DIACHI, NGAYSINH, TIENLUONG, SDT, LOAINV, USERNAME, PASS, NVQL) values ('Ruthanne Tettersell', '517 Burning Wood Trail', '6/2/2020', 108, 33530125, 4, 'rte', '123456', 2);
GO

insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Pea - Snow', 15, 79, 5,10,120,0,40,3);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Kolrabi', 25, 68, 9,20,110,0,40,1);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Island Oasis - Wildberry', 44, 91, 9,30,110,0,40,1);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Oil - Grapeseed Oil', 33, 68, 10,40,150,3,50,1);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Marsala - Sperone, Fine, D.o.c.', 12, 96, 10,30,70,15,60,4);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Compound - Raspberry', 47, 57, 5,40,120,20,90,1);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Shrimp - Prawn', 22, 63, 9,25,125,16,45,4);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Cheese - Brie,danish', 46, 53, 10,30,130,11,85,2);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Gherkin', 49, 64, 5,5,100,33,69,3);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Lobster - Base', 48, 69, 9,10,150,4,40,2);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('King Crab', 49, 2, 5,10,100,33,69,5);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('CatFish', 41, 3, 5,15,100,33,77,4);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Cheese Cake 1', 10, 5, 5,15,100,33,20,5);
insert into SANPHAM (TENSP, DONGIA, SLTONKHO, NVQL,SLTOITHIEU,SLTOIDA,SOLUONGTRA,SOLUONGTRATOIDA,NCC) values ('Lobster', 25, 3, 5,15,100,33,15,4);
GO

insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Daphnée', 'cstading0@clickbank.net', '2002-08-28', '27 Barnett Hill');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Régine', 'adevillier1@europa.eu', '1982-07-17', '2161 Del Mar Road');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Marie-ève', 'zmaltman2@wikispaces.com', '1984-12-03', '07382 Meadow Ridge Circle');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Séverine', 'nlongstaff3@eventbrite.com', '1994-01-19', '8576 Golf View Avenue');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Andréanne', 'dduckinfield4@wiley.com', '1973-04-12', '88 Bobwhite Terrace');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Méryl', 'eelsop5@paginegialle.it', '1964-12-12', '305 Londonderry Terrace');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Dorothée', 'cgainsford6@zimbio.com', '2016-11-08', '8 Luster Way');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Pò', 'sjeary7@reference.com', '1969-03-02', '37 Meadow Vale Park');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Cécilia', 'sbrearty8@unc.edu', '1950-06-13', '586 Valley Edge Lane');
insert into KHACHHANG (TENKH, EMAIL, NGAYSINH, DIACHI) values ('Uò', 'ltremontana9@infoseek.co.jp', '1999-09-11', '85614 Anthes Court');
GO

insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('7/8/2020', 526, 521, 1);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('1/31/2020', 791, 513, 1);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('3/27/2020', 893, 674, 0);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('12/7/2019', 682, 755, 1);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('6/8/2020', 291, 401, 1);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('8/13/2020', 489, 379, 0);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('1/21/2020', 271, 278, 1);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('2/8/2020', 973, 791, 0);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('9/19/2019', 270, 998, 1);
insert into DONHANG (NGAYLAP, TONGSOLUONG, TONGTIEN, TRANGTHAI) values ('8/26/2019', 318, 389, 1);
GO

insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (1, 8, 1, 213);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (2, 10, 2, 901);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (3, 9, 7, 617);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (4, 5, 1, 619);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (5, 1, 5, 818);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (6, 6, 4, 137);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (7, 5, 1, 365);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (8, 10, 9, 208);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (9, 6, 10, 794);
insert into CHITIETDONHANG (MADH, MASP, SOLUONG, THANHTIEN) values (10, 9, 7, 202);
GO

insert into BINHLUAN(HOTEN,EMAIL,DIACHI,NOIDUNG,MASP,NGAYBL,PHANLOAI) values('NGUYEN VAN A','VANA@GMAIL.COM','123 NGUYEN VAN CU, PHUONG 4, QUAN 5','SAN PHAM CHAT LUONG',1,'2019/01/01',0);
GO

insert into HOPDONG_QUANGCAO (TENDOITAC, NGAYLAP, VITRIDANGQC,THOIHAN) values ('Roombo', '11/28/2019', 'https://shop-pro.jp/adipiscing/elit/proin.html?tortor=sollicitudin&risus=mi&dapibus=sit&augue=amet&vel=lobortis&accumsan=sapien&tellus=sapien&nisi=non&eu=mi&orci=integer&mauris=ac&lacinia=neque&sapien=duis&quis=bibendum&libero=morbi&nullam=non&sit=quam&amet=nec&turpis=dui&elementum=luctus&ligula=rutrum&vehicula=nulla&consequat=tellus&morbi=in&a=sagittis&ipsum=dui&integer=vel&a=nisl&nibh=duis&in=ac&quis=nibh',30);
insert into HOPDONG_QUANGCAO (TENDOITAC, NGAYLAP, VITRIDANGQC,THOIHAN) values ('Kazio', '9/13/2019', 'https://github.com/donec/vitae/nisi/nam.png?interdum=et&eu=eros&tincidunt=vestibulum&in=ac&leo=est&maecenas=lacinia&pulvinar=nisi&lobortis=venenatis&est=tristique&phasellus=fusce&sit=congue&amet=diam&erat=id&nulla=ornare&tempus=imperdiet&vivamus=sapien&in=urna&felis=pretium&eu=nisl&sapien=ut&cursus=volutpat&vestibulum=sapien&proin=arcu&eu=sed&mi=augue',30);
insert into HOPDONG_QUANGCAO (TENDOITAC, NGAYLAP, VITRIDANGQC,THOIHAN) values ('Omba', '1/21/2020', 'https://soundcloud.com/nulla/neque/libero.json?et=erat&magnis=tortor&dis=sollicitudin&parturient=mi&montes=sit&nascetur=amet&ridiculus=lobortis&mus=sapien&vivamus=sapien&vestibulum=non&sagittis=mi&sapien=integer&cum=ac&sociis=neque&natoque=duis&penatibus=bibendum&et=morbi&magnis=non&dis=quam&parturient=nec&montes=dui&nascetur=luctus&ridiculus=rutrum&mus=nulla&etiam=tellus&vel=in&augue=sagittis&vestibulum=dui&rutrum=vel&rutrum=nisl',30);
GO

insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN, SOTK, NGANHANG, TENCHUTHE, MADH) values (8, 648, 'ONLINE', '2/1/2020','124536985','agribank','Luong',1);
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN) values (5, 518, 'COD', '7/20/2020');
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN) values (6, 327, 'COD', '12/6/2019');
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN) values (10, 483, 'COD', '4/19/2020');
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN, SOTK, NGANHANG, TENCHUTHE, MADH) values (2, 605, 'ONLINE', '1/22/2020','426598632','vietcombank','Quan',5);
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN) values (8, 854, 'COD', '12/4/2019');
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN, SOTK, NGANHANG, TENCHUTHE, MADH) values (7, 395, 'ONLINE', '1/18/2020','987562345','vietcombank','Ngon',7);
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN) values (4, 331, 'COD', '2/16/2020');
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN) values (4, 514, 'COD', '1/19/2020');
insert into LICHSU_THANHTOAN_KHACHHANG (MAKH, TONGTIEN, HINHTHUC, THOIGIAN, SOTK, NGANHANG, TENCHUTHE, MADH) values (3, 563, 'ONLINE', '1/6/2020','123547895','sacombank','Phuong',10);
GO

insert into LICHSU_KHACH_TRAHANG (MAKH, MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH) values (1, 7, 1, 'san pham kem chat luong', '2/1/2020', 7);
insert into LICHSU_KHACH_TRAHANG (MAKH, MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH) values (8, 2, 2, 'san pham kem chat luong', '5/24/2020', 10);
GO

insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Dacryocystorhinostomy [DCR]', 1, '11/2/2019', 9);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Simple suture of common bile duct', 1, '5/3/2020', 4);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Insertion of indwelling urinary catheter', 3, '4/18/2020', 5);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Fitting of orthotic device', 1, '7/11/2020', 4);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Packing of external auditory canal', 1, '12/20/2019', 5);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Excision of lacrimal sac and passage', 3, '8/13/2020', 5);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Excision of aneurysm of heart', 2, '6/23/2020', 4);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Evacuation of obstetrical incisional hematoma of perineum', 2, '12/10/2019', 4);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('ontrast vasogram', 1, '3/22/2020', 9);
insert into TINNHAN_QUANGCAO ( NOIDUNG, NGUOIGUI, NGAYGUI, NGUOINHAN) values ('Local excision of other lesion or tissue of esophagus', 1, '9/30/2019', 1);
GO

insert into TINDANG_QUANGCAO (NOIDUNG, NGUOIDANG, NGAYDANG, NGAYSUA, MAHOPDONG) values ('Other primary cardiomyopathies', 4, '5/21/2020', '9/15/2019', 1);
insert into TINDANG_QUANGCAO (NOIDUNG, NGUOIDANG, NGAYDANG, NGAYSUA, MAHOPDONG) values ('Tuberculosis of other female genital organs, bacteriological or histological examination unknown (at present)', 3, '10/17/2019','3/8/2020', 2);
insert into TINDANG_QUANGCAO (NOIDUNG, NGUOIDANG, NGAYDANG, NGAYSUA, MAHOPDONG) values ('Open fracture of six ribs', 5, '7/29/2020', '8/4/2020', 3);
GO

insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (9, '7/27/2020', 541, 5, 1, 1,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (5, '7/6/2020', 180, 5, 2, 1,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (5, '2/7/2020', 799, 5, 2, 1,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (5, '7/26/2020', 708, 5, 0, 4,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (3, '12/12/2019', 404, 5, 0, 2,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (7, '10/11/2019', 548, 4, 1, 3,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (5, '12/4/2019', 863, 6, 0, 3,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (6, '3/19/2020', 589, 4, 0, 5,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (5, '5/27/2020', 369, 4, 0, 1,'HET HANG',NULL);
insert into LICHSU_NHAP_NHACUNGCAP (MASP, NGAYNHAP, SOLUONG, NVPHUTRACH, XACNHAN, NCC,LYDONHAPHANG,QUANLY) values (10, '10/21/2019', 714, 5, 2, 2,'HET HANG',NULL);
GO

insert into LICHSU_TRA_NHACUNGCAP (MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH, XACNHAN, NCC,QUANLY) values (1, 101, 'LOI DO NHA CUNG CAP', '7/18/2020', 1, 2, 2,NULL);
insert into LICHSU_TRA_NHACUNGCAP (MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH, XACNHAN, NCC,QUANLY) values (10, 188, 'LOI DO NHA CUNG CAP', '2/10/2020', 3, 0, 2,NULL);
insert into LICHSU_TRA_NHACUNGCAP (MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH, XACNHAN, NCC,QUANLY) values (9, 130, 'LOI DO NHA CUNG CAP', '8/14/2020', 2, 0, 4,NULL);
insert into LICHSU_TRA_NHACUNGCAP (MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH, XACNHAN, NCC,QUANLY) values (10, 197, 'LOI DO NHA CUNG CAP', '9/27/2019', 1, 1, 5,NULL);
insert into LICHSU_TRA_NHACUNGCAP (MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH, XACNHAN, NCC,QUANLY) values (3, 154, 'LOI DO NHA CUNG CAP', '1/8/2020', 1, 0, 1,NULL);
insert into LICHSU_TRA_NHACUNGCAP (MASP, SOLUONG, LYDOTRA, NGAYTRA, NVPHUTRACH, XACNHAN, NCC,QUANLY) values (3, 154, 'LOI DO NHA CUNG CAP', '1/8/2020', 1, 0, 1,NULL);
GO


--drop function Get_ID_KH
--go
CREATE Function Get_ID_KH(@email  varchar(50))
Returns int
AS	
BEGIN   
	declare  @idkh int = 0;
	select @idkh = MAKH from KHACHHANG where EMAIL = @email;
	if ( @idkh != 0)
		return @idkh;
	else
	set @idkh = (select count(MAKH) from KHACHHANG);
	set @idkh = @idkh;
	return @idkh;
END
GO
--drop function Get_ID_DH
--go
CREATE Function Get_ID_DH()
Returns int
AS	
BEGIN   
	declare  @idDh int;
	set @idDh = (select  COUNT(MADH) from DONHANG) ;


		return @idDh;

END
GO

--drop function GET_STATUS_BILL
--go
CREATE Function GET_STATUS_BILL()
Returns VARCHAR
AS	
BEGIN   
	declare  @idDh int;
	declare  @status varchar;
	set @idDh = (select  COUNT(MADH) from DONHANG) ;
	set @status = (select TRANGTHAI from DONHANG where MADH = @idDh);
return @status;

END
GO


--drop function Get_TONG_SP 
--go
CREATE Function Get_TONG_SP(@madh int)
Returns int
AS	
BEGIN   
	declare  @idDh int;
	set @idDH = (select  sum(TONGTIEN) from DONHANG WHERE MADH = @madh);
	return @idDh;
END
GO